version: '3.8'

services:
  db:
    image: mysql:8.0.36
    container_name: auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authdb
    ports:
      - "3307:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth-net

  api:
    build: .
    container_name: go-auth-api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - auth-net

networks:
  auth-net:
    driver: bridge
